name: Snyk NuGet Security Scan

on:
  push:
    branches: 
      - main
      - master 
  pull_request:
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Dotnet restore
        run: Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object { dotnet restore $_.FullName }
          
      - name: Install Snyk
        run: npm install -g snyk
        
      - name: Run Snyk test for all NuGet projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: Get-ChildItem -Path . -Recurse -Filter "project.assets.json" | ForEach-Object { snyk test --file="$($_.FullName)" --package-manager=nuget }

      - name: Run Snyk test (NuGet)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --detection-depth=20

      - name: Snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor

